# Generated by Django 2.2.24 on 2021-12-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricBoardFunctionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionName', models.CharField(max_length=32)),
                ('functionKey', models.CharField(max_length=16)),
                ('typeKey', models.CharField(max_length=16)),
                ('productType', models.CharField(max_length=16)),
                ('isDefault', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_user_id', models.CharField(max_length=16, null=True)),
                ('update_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricBoardFunctionTypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=32)),
                ('typeKey', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=32)),
                ('priority', models.IntegerField()),
                ('isRequired', models.IntegerField()),
                ('isMultiple', models.IntegerField()),
                ('productType', models.CharField(max_length=16)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_user_id', models.CharField(max_length=16, null=True)),
                ('update_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functionName', models.CharField(max_length=32)),
                ('functionKey', models.CharField(max_length=16)),
                ('typeKey', models.CharField(max_length=16)),
                ('productType', models.CharField(max_length=16)),
                ('isDefault', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_user_id', models.CharField(max_length=16, null=True)),
                ('update_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionTypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=32)),
                ('typeKey', models.CharField(max_length=16)),
                ('desc', models.CharField(max_length=32)),
                ('priority', models.IntegerField()),
                ('isRequired', models.IntegerField()),
                ('isMultiple', models.IntegerField()),
                ('productType', models.CharField(max_length=16)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_user_id', models.CharField(max_length=16, null=True)),
                ('update_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=32)),
                ('productTypeName', models.CharField(max_length=32)),
                ('categoryType', models.CharField(max_length=32)),
                ('branch', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('sN8', models.CharField(max_length=32)),
                ('lifecycleStage', models.CharField(max_length=32)),
                ('saleChannel', models.CharField(max_length=128, null=True)),
                ('functionIds', models.CharField(max_length=128, null=True)),
                ('scenarioIds', models.CharField(max_length=128, null=True)),
                ('voiceFunctionIds', models.CharField(max_length=128, null=True)),
                ('ecologyEntranceIds', models.CharField(max_length=128, null=True)),
                ('sensorIds', models.CharField(max_length=128, null=True)),
                ('electricBoardFunctionIds', models.CharField(max_length=128, null=True)),
                ('pic', models.CharField(max_length=32, null=True)),
                ('powerBoardCode', models.CharField(max_length=32, null=True)),
                ('displayBoardCode', models.CharField(max_length=32, null=True)),
                ('wifiModuleCode', models.CharField(max_length=32, null=True)),
                ('networkingMode', models.CharField(max_length=32, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_user_id', models.CharField(max_length=16, null=True)),
                ('update_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('actorUserId', models.CharField(max_length=128)),
                ('auditGroupId', models.CharField(max_length=128)),
                ('auditGroupUserIds', models.CharField(max_length=128)),
                ('productType', models.CharField(max_length=16)),
                ('productModel', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('createUserId', models.CharField(max_length=16, null=True)),
                ('updateUserId', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
