# Generated by Django 3.2.10 on 2022-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functiondata',
            name='functionDesc',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='functiontypedata',
            name='dataType',
            field=models.CharField(default='String', max_length=16),
        ),
    ]
