# Generated by Django 3.2.10 on 2022-01-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20220107_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='functiondata',
            name='isDisable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='functiondata',
            name='isDefault',
            field=models.IntegerField(default=0),
        ),
    ]
