# Generated by Django 3.2.10 on 2022-01-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_auto_20220107_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='hasBuzzer',
            field=models.IntegerField(default=0, verbose_name='是否有蜂鸣器'),
        ),
        migrations.AddField(
            model_name='productdata',
            name='hasElectricLeakageProtect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productdata',
            name='hasFlowSensor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productdata',
            name='heatingTubeType',
            field=models.IntegerField(null=True),
        ),
    ]
