# Generated by Django 3.2.10 on 2022-01-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_auto_20220109_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingTubeTypeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('tubeCount', models.IntegerField()),
                ('topTubePower', models.IntegerField()),
                ('middleTubePower', models.IntegerField()),
                ('bottomTubePower', models.IntegerField()),
                ('onlyTubePower', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_user_id', models.CharField(max_length=16, null=True)),
                ('update_user_id', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
