# Generated by Django 3.2.10 on 2022-01-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_wifimoduletypedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifimoduletypedata',
            name='name',
        ),
        migrations.AddField(
            model_name='wifimoduletypedata',
            name='mcuType',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
