# Generated by Django 3.2.10 on 2022-01-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_auto_20220109_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifimoduletypedata',
            name='desc',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
