# Generated by Django 3.2.10 on 2022-01-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_wifimoduletypedata_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_authorization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmDevelopTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('actor_user_id', models.IntegerField(blank=True, null=True)),
                ('audit_user_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('current_handle_finish_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_handle_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_handler_role', models.CharField(blank=True, max_length=255, null=True)),
                ('product_ecology_entrance_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('product_function_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('product_model', models.CharField(blank=True, max_length=255, null=True)),
                ('product_scenario_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('product_sensor_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('product_voice_function_ids', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor_time', models.DateTimeField(blank=True, null=True)),
                ('sponsor_user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fm_develop_task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmDevelopTaskAuditGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('create_user_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fm_develop_task_audit_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmDevelopTaskAuditGroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('audit_group_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fm_develop_task_audit_group_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmDevelopTaskProcessContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('develop_task_id', models.IntegerField(blank=True, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('opinion', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fm_develop_task_process_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_code', models.CharField(blank=True, max_length=255, null=True)),
                ('key_name', models.CharField(blank=True, max_length=255, null=True)),
                ('value_code', models.CharField(blank=True, max_length=255, null=True)),
                ('value_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_dictionary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmEncologyEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_encology_entrance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_function',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmProductEcologyEntrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecology_entrance_id', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('product_sn8', models.CharField(blank=True, max_length=255, null=True)),
                ('product_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fm_product_ecology_entrance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmProductFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_id', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('product_sn8', models.CharField(blank=True, max_length=255, null=True)),
                ('product_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fm_product_function',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('lifecycle_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_channel', models.CharField(blank=True, max_length=255, null=True)),
                ('sn8', models.CharField(blank=True, max_length=255, null=True)),
                ('pic', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('product_version', models.CharField(blank=True, max_length=255, null=True)),
                ('dishwasher_property', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'fm_product_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmProductScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('scenario_id', models.IntegerField(blank=True, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('product_sn8', models.CharField(blank=True, max_length=255, null=True)),
                ('product_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fm_product_scenario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmProductSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('sensor_id', models.IntegerField(blank=True, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('product_sn8', models.CharField(blank=True, max_length=255, null=True)),
                ('product_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fm_product_sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmProductVoiceFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('voice_function_id', models.IntegerField(blank=True, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
                ('product_sn8', models.CharField(blank=True, max_length=255, null=True)),
                ('product_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fm_product_voice_function',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_scenario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('type_code', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=1024, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmUserAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_user_authorization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmVoiceFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fm_voice_function',
                'managed': False,
            },
        ),
    ]
