# Generated by Django 3.2.10 on 2022-01-12 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0010_fmauthorization_fmdeveloptask_fmdeveloptaskauditgroup_fmdeveloptaskauditgroupuser_fmdeveloptaskproce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fmauthorization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmdeveloptask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmdeveloptaskauditgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmdeveloptaskauditgroupuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmdeveloptaskprocesscontent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmdictionary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmencologyentrance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmfunction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmproductecologyentrance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmproductfunction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmproductinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmproductscenario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmproductsensor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmproductvoicefunction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmscenario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmsensor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmuserauthorization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fmvoicefunction',
            options={},
        ),
    ]
