# Generated by Django 3.2.10 on 2022-01-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0011_auto_20220112_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fmfunction',
            old_name='function_name',
            new_name='functionName',
        ),
        migrations.RenameField(
            model_name='fmfunction',
            old_name='type_code',
            new_name='typeCode',
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='functionDesc',
            field=models.CharField(db_column='function_desc', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='functionKey',
            field=models.CharField(db_column='function_key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='isDefault',
            field=models.IntegerField(db_column='is_default', default=0),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='isDisable',
            field=models.IntegerField(db_column='is_disable', default=0),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='typeKey',
            field=models.CharField(db_column='type_key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmfunction',
            name='functionName',
            field=models.CharField(blank=True, db_column='function_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmfunction',
            name='typeCode',
            field=models.CharField(blank=True, db_column='type_code', max_length=255, null=True),
        ),
    ]
