# Generated by Django 3.2.10 on 2022-01-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_auto_20220113_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fmauthorization',
            old_name='auth_code',
            new_name='authCode',
        ),
        migrations.RenameField(
            model_name='fmauthorization',
            old_name='auth_name',
            new_name='authName',
        ),
        migrations.RenameField(
            model_name='fmauthorization',
            old_name='create_date_time',
            new_name='createDateTime',
        ),
        migrations.RenameField(
            model_name='fmauthorization',
            old_name='update_date_time',
            new_name='updateDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='actor_user_id',
            new_name='actorUserId',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='audit_user_ids',
            new_name='auditUserIds',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='create_date_time',
            new_name='createDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='current_handle_finish_user_id',
            new_name='currentHandleFinishUserId',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='current_handle_user_id',
            new_name='currentHandleUserId',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='current_handler_role',
            new_name='currentHandlerRole',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='product_ecology_entrance_ids',
            new_name='productEcologyEntranceIds',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='product_function_ids',
            new_name='productFunctionIds',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='product_model',
            new_name='productModel',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='product_scenario_ids',
            new_name='productScenarioIds',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='product_sensor_ids',
            new_name='productSensorIds',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='product_voice_function_ids',
            new_name='productVoiceFunctionIds',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='sponsor_time',
            new_name='sponsorTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptask',
            old_name='update_date_time',
            new_name='updateDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskauditgroup',
            old_name='create_user_id',
            new_name='createUserId',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskauditgroup',
            old_name='group_name',
            new_name='groupName',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskauditgroup',
            old_name='update_date_time',
            new_name='updateDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskauditgroupuser',
            old_name='audit_group_id',
            new_name='auditGroupId',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskauditgroupuser',
            old_name='create_date_time',
            new_name='createDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskauditgroupuser',
            old_name='update_date_time',
            new_name='updateDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskauditgroupuser',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskprocesscontent',
            old_name='create_date_time',
            new_name='createDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskprocesscontent',
            old_name='develop_task_id',
            new_name='developTaskId',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskprocesscontent',
            old_name='update_date_time',
            new_name='updateDateTime',
        ),
        migrations.RenameField(
            model_name='fmdeveloptaskprocesscontent',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='fmdictionary',
            old_name='create_date_time',
            new_name='createDateTime',
        ),
        migrations.RenameField(
            model_name='fmdictionary',
            old_name='key_code',
            new_name='keyCode',
        ),
        migrations.RenameField(
            model_name='fmdictionary',
            old_name='key_name',
            new_name='keyName',
        ),
        migrations.RenameField(
            model_name='fmdictionary',
            old_name='update_date_time',
            new_name='updateDateTime',
        ),
        migrations.RenameField(
            model_name='fmdictionary',
            old_name='value_code',
            new_name='valueCode',
        ),
        migrations.RenameField(
            model_name='fmdictionary',
            old_name='value_name',
            new_name='valueName',
        ),
        migrations.RenameField(
            model_name='fmencologyentrance',
            old_name='create_date_time',
            new_name='createDateTime',
        ),
        migrations.RemoveField(
            model_name='fmdeveloptask',
            name='sponsor_user_id',
        ),
        migrations.RemoveField(
            model_name='fmdeveloptaskauditgroup',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmencologyentrance',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmfunction',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmfunction',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductecologyentrance',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductecologyentrance',
            name='ecology_entrance_id',
        ),
        migrations.RemoveField(
            model_name='fmproductecologyentrance',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='fmproductecologyentrance',
            name='product_sn8',
        ),
        migrations.RemoveField(
            model_name='fmproductecologyentrance',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='fmproductecologyentrance',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductfunction',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductfunction',
            name='function_id',
        ),
        migrations.RemoveField(
            model_name='fmproductfunction',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='fmproductfunction',
            name='product_sn8',
        ),
        migrations.RemoveField(
            model_name='fmproductfunction',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='fmproductfunction',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='dishwasher_property',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='lifecycle_stage',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='sale_channel',
        ),
        migrations.RemoveField(
            model_name='fmproductinfo',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductscenario',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductscenario',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='fmproductscenario',
            name='product_sn8',
        ),
        migrations.RemoveField(
            model_name='fmproductscenario',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='fmproductscenario',
            name='scenario_id',
        ),
        migrations.RemoveField(
            model_name='fmproductscenario',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductsensor',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductsensor',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='fmproductsensor',
            name='product_sn8',
        ),
        migrations.RemoveField(
            model_name='fmproductsensor',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='fmproductsensor',
            name='sensor_id',
        ),
        migrations.RemoveField(
            model_name='fmproductsensor',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductvoicefunction',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductvoicefunction',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='fmproductvoicefunction',
            name='product_sn8',
        ),
        migrations.RemoveField(
            model_name='fmproductvoicefunction',
            name='product_version',
        ),
        migrations.RemoveField(
            model_name='fmproductvoicefunction',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmproductvoicefunction',
            name='voice_function_id',
        ),
        migrations.RemoveField(
            model_name='fmscenario',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmscenario',
            name='scenario_name',
        ),
        migrations.RemoveField(
            model_name='fmscenario',
            name='type_code',
        ),
        migrations.RemoveField(
            model_name='fmscenario',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmsensor',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmsensor',
            name='sensor_name',
        ),
        migrations.RemoveField(
            model_name='fmsensor',
            name='type_code',
        ),
        migrations.RemoveField(
            model_name='fmsensor',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmuser',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmuser',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmuser',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='fmuserauthorization',
            name='auth_id',
        ),
        migrations.RemoveField(
            model_name='fmuserauthorization',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmuserauthorization',
            name='update_date_time',
        ),
        migrations.RemoveField(
            model_name='fmuserauthorization',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='fmvoicefunction',
            name='create_date_time',
        ),
        migrations.RemoveField(
            model_name='fmvoicefunction',
            name='update_date_time',
        ),
        migrations.AddField(
            model_name='fmdeveloptask',
            name='sponsorUserId',
            field=models.IntegerField(blank=True, db_column='sponsor_user_id', null=True),
        ),
        migrations.AddField(
            model_name='fmdeveloptaskauditgroup',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmencologyentrance',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductecologyentrance',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductecologyentrance',
            name='ecologyEntranceId',
            field=models.IntegerField(blank=True, db_column='ecology_entrance_id', null=True),
        ),
        migrations.AddField(
            model_name='fmproductecologyentrance',
            name='productCode',
            field=models.CharField(blank=True, db_column='product_code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductecologyentrance',
            name='productSn8',
            field=models.CharField(blank=True, db_column='product_sn8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductecologyentrance',
            name='productVersion',
            field=models.CharField(blank=True, db_column='product_version', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductecologyentrance',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductfunction',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductfunction',
            name='functionId',
            field=models.IntegerField(blank=True, db_column='function_id', null=True),
        ),
        migrations.AddField(
            model_name='fmproductfunction',
            name='productCode',
            field=models.CharField(blank=True, db_column='product_code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductfunction',
            name='productSn8',
            field=models.CharField(blank=True, db_column='product_sn8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductfunction',
            name='productVersion',
            field=models.CharField(blank=True, db_column='product_version', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductfunction',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='dishwasherProperty',
            field=models.CharField(blank=True, db_column='dishwasher_property', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='lifecycleStage',
            field=models.CharField(blank=True, db_column='lifecycle_stage', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='productCategory',
            field=models.CharField(blank=True, db_column='product_category', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='productType',
            field=models.CharField(blank=True, db_column='product_type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='productVersion',
            field=models.CharField(blank=True, db_column='product_version', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='saleChannel',
            field=models.CharField(blank=True, db_column='sale_channel', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductinfo',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductscenario',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductscenario',
            name='productCode',
            field=models.CharField(blank=True, db_column='product_code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductscenario',
            name='productSn8',
            field=models.CharField(blank=True, db_column='product_sn8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductscenario',
            name='productVersion',
            field=models.CharField(blank=True, db_column='product_version', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductscenario',
            name='scenarioId',
            field=models.IntegerField(blank=True, db_column='scenario_id', null=True),
        ),
        migrations.AddField(
            model_name='fmproductscenario',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductsensor',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductsensor',
            name='productCode',
            field=models.CharField(blank=True, db_column='product_code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductsensor',
            name='productSn8',
            field=models.CharField(blank=True, db_column='product_sn8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductsensor',
            name='productVersion',
            field=models.CharField(blank=True, db_column='product_version', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductsensor',
            name='sensorId',
            field=models.IntegerField(blank=True, db_column='sensor_id', null=True),
        ),
        migrations.AddField(
            model_name='fmproductsensor',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductvoicefunction',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductvoicefunction',
            name='productCode',
            field=models.CharField(blank=True, db_column='product_code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductvoicefunction',
            name='productSn8',
            field=models.CharField(blank=True, db_column='product_sn8', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductvoicefunction',
            name='productVersion',
            field=models.CharField(blank=True, db_column='product_version', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmproductvoicefunction',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmproductvoicefunction',
            name='voiceFunction_id',
            field=models.IntegerField(blank=True, db_column='voice_function_id', null=True),
        ),
        migrations.AddField(
            model_name='fmscenario',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmscenario',
            name='scenarioName',
            field=models.CharField(blank=True, db_column='scenario_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmscenario',
            name='typeCode',
            field=models.CharField(blank=True, db_column='type_code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmscenario',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmsensor',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmsensor',
            name='sensorName',
            field=models.CharField(blank=True, db_column='sensor_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmsensor',
            name='typeCode',
            field=models.CharField(blank=True, db_column='type_code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmsensor',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmuser',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmuser',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmuser',
            name='userName',
            field=models.CharField(blank=True, db_column='user_name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmuserauthorization',
            name='authId',
            field=models.IntegerField(blank=True, db_column='auth_id', null=True),
        ),
        migrations.AddField(
            model_name='fmuserauthorization',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmuserauthorization',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmuserauthorization',
            name='userId',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
        migrations.AddField(
            model_name='fmvoicefunction',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AddField(
            model_name='fmvoicefunction',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmauthorization',
            name='authCode',
            field=models.CharField(blank=True, db_column='auth_code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmauthorization',
            name='authName',
            field=models.CharField(blank=True, db_column='auth_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmauthorization',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmauthorization',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='actorUserId',
            field=models.IntegerField(blank=True, db_column='actor_user_id', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='auditUserIds',
            field=models.CharField(blank=True, db_column='audit_user_ids', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='currentHandleFinishUserId',
            field=models.CharField(blank=True, db_column='current_handle_finish_user_id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='currentHandleUserId',
            field=models.CharField(blank=True, db_column='current_handle_user_id', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='currentHandlerRole',
            field=models.CharField(blank=True, db_column='current_handler_role', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='productEcologyEntranceIds',
            field=models.CharField(blank=True, db_column='product_ecology_entrance_ids', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='productFunctionIds',
            field=models.CharField(blank=True, db_column='product_function_ids', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='productModel',
            field=models.CharField(blank=True, db_column='product_model', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='productScenarioIds',
            field=models.CharField(blank=True, db_column='product_scenario_ids', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='productSensorIds',
            field=models.CharField(blank=True, db_column='product_sensor_ids', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='productVoiceFunctionIds',
            field=models.CharField(blank=True, db_column='product_voice_function_ids', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='sponsorTime',
            field=models.DateTimeField(blank=True, db_column='sponsor_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptask',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskauditgroup',
            name='createUserId',
            field=models.IntegerField(blank=True, db_column='create_user_id', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskauditgroup',
            name='groupName',
            field=models.CharField(blank=True, db_column='group_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskauditgroup',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskauditgroupuser',
            name='auditGroupId',
            field=models.IntegerField(blank=True, db_column='audit_group_id', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskauditgroupuser',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskauditgroupuser',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskauditgroupuser',
            name='userId',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskprocesscontent',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskprocesscontent',
            name='developTaskId',
            field=models.IntegerField(blank=True, db_column='develop_task_id', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskprocesscontent',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdeveloptaskprocesscontent',
            name='userId',
            field=models.IntegerField(blank=True, db_column='user_id', null=True),
        ),
        migrations.AlterField(
            model_name='fmdictionary',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdictionary',
            name='keyCode',
            field=models.CharField(blank=True, db_column='key_code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdictionary',
            name='keyName',
            field=models.CharField(blank=True, db_column='key_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdictionary',
            name='updateDateTime',
            field=models.DateTimeField(auto_now=True, db_column='update_date_time', null=True),
        ),
        migrations.AlterField(
            model_name='fmdictionary',
            name='valueCode',
            field=models.CharField(blank=True, db_column='value_code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmdictionary',
            name='valueName',
            field=models.CharField(blank=True, db_column='value_name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmencologyentrance',
            name='createDateTime',
            field=models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True),
        ),
    ]
