# Generated by Django 3.2.10 on 2022-01-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0013_auto_20220113_1243'),
    ]

    operations = [
    ]
