# Generated by Django 3.2.10 on 2022-01-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0014_auto_20220113_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmfunction',
            name='functionDesc',
            field=models.CharField(db_column='function_desc', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='functionKey',
            field=models.CharField(db_column='function_key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='isDefault',
            field=models.IntegerField(db_column='is_default', default=0),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='isDisable',
            field=models.IntegerField(db_column='is_disable', default=0),
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='typeKey',
            field=models.CharField(db_column='type_key', max_length=255, null=True),
        ),
    ]
