# Generated by Django 3.2.10 on 2022-01-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0015_auto_20220113_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmFunctionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(db_column='type_name', max_length=255)),
                ('typeKey', models.CharField(db_column='type_key', max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('isRequired', models.IntegerField(db_column='is_required')),
                ('isMultiple', models.IntegerField(db_column='is_multiple')),
                ('productType', models.CharField(db_column='product_type', max_length=255)),
                ('dataType', models.CharField(db_column='data_type', default='String', max_length=16)),
                ('createDateTime', models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True, db_column='update_date_time', null=True)),
            ],
            options={
                'db_table': 'fm_function_type',
            },
        ),
    ]
