# Generated by Django 3.2.10 on 2022-01-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0017_fmdeveloptaskpruduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricboardfunctiondata',
            name='dataType',
            field=models.CharField(db_column='data_type', default='String', max_length=16),
        ),
    ]
