# Generated by Django 3.2.10 on 2022-01-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0018_electricboardfunctiondata_datatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmfunction',
            name='typeKey',
        ),
        migrations.AddField(
            model_name='fmfunction',
            name='functionValue',
            field=models.CharField(db_column='function_value', max_length=255, null=True),
        ),
    ]
