# Generated by Django 3.2.10 on 2022-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0019_auto_20220114_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fmfunctiontype',
            name='priority',
        ),
        migrations.AddField(
            model_name='fmfunctiontype',
            name='displayPriority',
            field=models.IntegerField(db_column='display_priority', default=0),
        ),
        migrations.AddField(
            model_name='fmfunctiontype',
            name='insertPriority',
            field=models.IntegerField(db_column='insert_priority', default=0),
        ),
    ]
