# Generated by Django 3.2.10 on 2022-01-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0020_auto_20220114_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmfunctiontype',
            name='insertTemplate',
            field=models.CharField(db_column='fix_template', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmfunctiontype',
            name='isMultiple',
            field=models.IntegerField(db_column='is_multiple', default=0),
        ),
        migrations.AlterField(
            model_name='fmfunctiontype',
            name='isRequired',
            field=models.IntegerField(db_column='is_required', default=0),
        ),
    ]
