# Generated by Django 3.2.10 on 2022-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0021_auto_20220114_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmfunctiontype',
            name='insertTemplate',
            field=models.CharField(db_column='insert_template', max_length=255, null=True),
        ),
    ]
