# Generated by Django 3.2.10 on 2022-01-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0022_alter_fmfunctiontype_inserttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmfunctiontype',
            name='componentType',
            field=models.CharField(db_column='component_type', max_length=255, null=True),
        ),
    ]
