# Generated by Django 3.2.10 on 2022-01-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0023_fmfunctiontype_componenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmElectricBoardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(db_column='type_name', max_length=255)),
                ('typeKey', models.CharField(db_column='type_key', max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('displayPriority', models.IntegerField(db_column='display_priority', default=0)),
                ('isRequired', models.IntegerField(db_column='is_required')),
                ('productType', models.CharField(db_column='product_type', max_length=255)),
                ('dataType', models.CharField(db_column='data_type', default='String', max_length=16)),
                ('createDateTime', models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True, db_column='update_date_time', null=True)),
            ],
            options={
                'db_table': 'fm_electric_board_info',
            },
        ),
        migrations.CreateModel(
            name='FmProductElectricBoardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productCode', models.CharField(blank=True, db_column='product_code', max_length=255, null=True)),
                ('productSn8', models.CharField(blank=True, db_column='product_sn8', max_length=255, null=True)),
                ('productVersion', models.CharField(blank=True, db_column='product_version', max_length=255, null=True)),
                ('infoName', models.CharField(db_column='info_name', max_length=255)),
                ('infoKey', models.CharField(db_column='info_key', max_length=255)),
                ('infoValue', models.CharField(db_column='info_value', max_length=255)),
                ('productType', models.CharField(db_column='product_type', max_length=255)),
                ('createDateTime', models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True, db_column='update_date_time', null=True)),
            ],
            options={
                'db_table': 'fm_function_electric_board_info',
            },
        ),
    ]
