# Generated by Django 3.2.10 on 2022-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0024_fmelectricboardinfo_fmproductelectricboardinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmelectricboardinfo',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fmelectricboardinfo',
            name='isRequired',
            field=models.IntegerField(db_column='is_required', default=0),
        ),
    ]
