# Generated by Django 3.2.10 on 2022-01-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0025_auto_20220115_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricBoardFunctionData',
        ),
        migrations.DeleteModel(
            name='ElectricBoardFunctionTypeData',
        ),
        migrations.DeleteModel(
            name='FunctionData',
        ),
        migrations.DeleteModel(
            name='FunctionTypeData',
        ),
        migrations.DeleteModel(
            name='TaskData',
        ),
    ]
