# Generated by Django 3.2.10 on 2022-01-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0026_auto_20220115_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductData',
        ),
        migrations.AddField(
            model_name='fmelectricboardinfo',
            name='componentType',
            field=models.CharField(db_column='component_type', max_length=255, null=True),
        ),
    ]
