# Generated by Django 3.2.10 on 2022-01-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0027_auto_20220115_2219'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fmproductelectricboardinfo',
            table='fm_product_electric_board_info',
        ),
    ]
