# Generated by Django 3.2.10 on 2022-01-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0028_alter_fmproductelectricboardinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='key', max_length=255)),
                ('value', models.CharField(db_column='value', max_length=255)),
                ('label', models.CharField(db_column='label', max_length=255)),
                ('desc', models.CharField(db_column='desc', max_length=255)),
                ('productType', models.CharField(db_column='product_type', max_length=255)),
                ('createDateTime', models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True, db_column='update_date_time', null=True)),
            ],
            options={
                'db_table': 'fm_selection',
            },
        ),
    ]
