# Generated by Django 3.2.10 on 2022-01-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0029_fmselection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FmSelection',
            new_name='FmSelectOption',
        ),
        migrations.AlterModelTable(
            name='fmselectoption',
            table='fm_select_option',
        ),
    ]
