# Generated by Django 3.2.10 on 2022-01-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0030_auto_20220116_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmselectoption',
            name='desc',
            field=models.CharField(db_column='desc', max_length=255, null=True),
        ),
    ]
