# Generated by Django 3.2.10 on 2022-01-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0031_alter_fmselectoption_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fmproductvoicefunction',
            old_name='voiceFunction_id',
            new_name='voiceFunctionId',
        ),
    ]
