# Generated by Django 3.2.10 on 2022-01-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0033_fmproductinfo_appstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmdeveloptask',
            name='hardwareEngineer',
            field=models.CharField(blank=True, db_column='hardware_engineer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmdeveloptask',
            name='planner',
            field=models.CharField(blank=True, db_column='planner', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmdeveloptask',
            name='pm',
            field=models.CharField(blank=True, db_column='pm', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmdeveloptask',
            name='productIds',
            field=models.CharField(blank=True, db_column='product_ids', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmdeveloptask',
            name='productType',
            field=models.CharField(blank=True, db_column='product_type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fmdeveloptask',
            name='softwareEngineer',
            field=models.CharField(blank=True, db_column='software_engineer', max_length=255, null=True),
        ),
    ]
