# Generated by Django 3.2.10 on 2022-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0034_auto_20220117_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmuser',
            name='nickName',
            field=models.CharField(blank=True, db_column='nick_name', max_length=255, null=True),
        ),
    ]
