# Generated by Django 3.2.4 on 2022-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0036_fmtaskqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmFileMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileId', models.CharField(blank=True, db_column='file_id', max_length=255, null=True)),
                ('filePath', models.CharField(blank=True, db_column='file_path', max_length=255, null=True)),
                ('fileName', models.CharField(blank=True, db_column='file_name', max_length=255, null=True)),
                ('createDateTime', models.DateTimeField(auto_now_add=True, db_column='create_date_time', null=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True, db_column='update_date_time', null=True)),
            ],
            options={
                'db_table': 'fm_file_map',
            },
        ),
    ]
